---

- include_tasks: create_cert.yml
  when: not ansible_local.certbot|d() or not ansible_local.certbot.letsencrypt_cert == certbot__domain

- name: Make sure facts directory exits
  file:
    path: '/etc/ansible/facts.d'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: Save Ansible local facts
  template:
    src: 'etc/ansible/facts.d/certbot.fact.j2'
    dest: '/etc/ansible/facts.d/certbot.fact'
    owner: 'root'
    group: 'root'
    mode: '0644'
