- name: Set pattern
  set_fact:
    __pattern: ".*{{ __v }}_to_merge$"


- block:
  - name: Reset tmp var
    set_fact:
      __tmp: {}

  - name: Merge dict based on pattern
    set_fact:
      __tmp: "{{ lookup('vars', item2) | combine(__tmp|default({})) }}"
    with_items: "{{ vars.keys() | select('match', __pattern) | list}}"
    loop_control:
      loop_var: item2

  - name: Set merged var
    set_fact:
      "{{ __v }}": "{{ __tmp | combine(vars[__v]|default({})) }}"
  when: __type == 'dict'

- block:
  - name: Reset tmp var
    set_fact:
      __tmp: []

  - name: Merge lists based on pattern
    set_fact:
      __tmp: "{{ lookup('vars', item2) | union(__tmp|default([])) }}"
      # __tmp: "{{ __vars[item2] | union(__tmp|default([])) }}"
    with_items: "{{ vars.keys() | select('match', __pattern) | list}}"
    loop_control:
      loop_var: item2

  - name: Set merged var
    set_fact:
      "{{ __v }}": "{{ __tmp | union(vars[__v]|default([])) }}"
  when: __type == 'list'


# vim: ft=ansible
