- name: "Install misc packages"
  apt:
    name:
      - "apt-transport-https"
      - "ca-certificates"
      - "curl"
      - "software-properties-common"
      - "python-service-identity"
      - "python-docker"

- name: "Add Docker GPG key"
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    state: present

- name: "Add Docker repository"
  apt_repository:
    repo: "deb https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} stable"
    state: present
    filename: docker

- name: "Install 'docker-ce'"
  apt:
    name: "docker-ce"
    update_cache: yes
